services:
  alpine:
    image: alpine:latest
    container_name: "alpine"
    tty: true
    stdin_open: true
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.alpine.loadbalancer.server.port=80"
      - "traefik.http.routers.alpine.rule=Host(`alpine.${DOMAIN}`)"
      - "traefik.http.routers.alpine.entrypoints=websecure"
      - "traefik.http.routers.alpine.tls=true"
      - "traefik.http.routers.alpine.tls.domains[0].main=${DOMAIN}"
      - "traefik.http.routers.alpine.tls.domains[0].sans=*.${DOMAIN}"
      - "traefik.http.routers.alpine.tls.certresolver=letsencryptresolver"
      # Get Real IP
      - "traefik.http.routers.alpine.middlewares=traefik-real-ip,fail2ban"
