volumes:
  gitea_db:
    driver: local
  gitea_app:
    driver: local

services:
  gitea_db:
    image: postgres:14
    container_name: gitea_db
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=Tm1tS6EPFQFHw9w3FLXbAEelfdqkqqTuGzF3g8yOcPjQ0J8j1ekIjSwnvUDt_gitea
      - POSTGRES_DB=gitea
    volumes:
      - gitea_db:/data

  gitea_server:
    image: gitea/gitea:1.22.2
    container_name: gitea_server
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=gitea_db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=Tm1tS6EPFQFHw9w3FLXbAEelfdqkqqTuGzF3g8yOcPjQ0J8j1ekIjSwnvUDt_gitea
      - GITEA__service__DISABLE_REGISTRATION=true
    restart: always
    volumes:
      - gitea_app:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - gitea_db
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"
      - "traefik.http.routers.gitea.rule=Host(`git.${DOMAIN}`)"
      - "traefik.http.routers.gitea.entrypoints=websecure"
      - "traefik.http.routers.gitea.tls=true"
      - "traefik.http.routers.gitea.tls.domains[0].main=${DOMAIN}"
      - "traefik.http.routers.gitea.tls.domains[0].sans=*.${DOMAIN}"
      - "traefik.http.routers.gitea.tls.certresolver=letsencryptresolver"
      # Get Real IP
      - "traefik.http.routers.gitea.middlewares=traefik-real-ip,fail2ban"
      # Expose SSH
      - "traefik.tcp.services.gitea-ssh.loadbalancer.server.port=2222"
      - "traefik.tcp.routers.gitea-ssh.entrypoints=ssh"
      - "traefik.tcp.routers.gitea-ssh.service=gitea-ssh"
      - "traefik.tcp.routers.gitea-ssh.rule=HostSNI(`*`)"
